services:
  placetw-discord-bot:
    image: ghcr.io/placetw/discord-bot:main
  restart: unless-stopped
  container_name: placetw-discord-bot
  volumes: 
    - ./discord-bot:/app
  env_file:
    - .env